name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: # 13 is Intel, 14 is Apple Silicon
        os: [ ubuntu-latest, macos-13, macos-14 ]
        python: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Create venv
        run: |
          python3 -m venv venv

      - name: Activate virtualenv
        run: |
          source venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - run: pip3 install .

      - name: Clone verifier repo
        uses: actions/checkout@v4
        with:
          repository: tinfoilsh/verifier
          ref: v0.0.21
          path: verifier

      - uses: actions/setup-go@v5
        with:
          go-version-file: verifier/go.mod

      - name: Install go bind tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/go-python/gopy@latest

      - name: Bind
        run: |
          cd verifier && gopy build -output=tinfoil_verifier -vm=python3 github.com/tinfoilsh/verifier/client
          ls -lah
          mv tinfoil_verifier ../tinfoil
          cd .. && rm -rf verifier

      - name: Build wheel
        run: |
          python3 -m build
          python3 rename.py

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinfoil-python-${{ matrix.os }}-${{ matrix.python }}
          path: ./dist/*.whl

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build_wheels
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Move artifacts
        run: |
          mv dist/**/*.whl dist
          rm -rf dist/tinfoil-python-*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
