name: Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]   # pick one stable Python

    # Expose secrets as plain ENV vars so we can gate on them
    env:
      TINFOIL_ENCLAVE: ${{ secrets.TINFOIL_ENCLAVE }}
      TINFOIL_REPO:    ${{ secrets.TINFOIL_REPO }}
      TINFOIL_API_KEY: ${{ secrets.TINFOIL_API_KEY }}

    steps:
      # ─── Gate: skip entire job if secrets aren’t set (e.g. forks) ────────
      - name: Check integration secrets
        id: gate
        run: |
          if [ -z "$TINFOIL_ENCLAVE" ] || [ -z "$TINFOIL_REPO" ]; then
            echo "run=false" >> $GITHUB_OUTPUT
          else
            echo "run=true"  >> $GITHUB_OUTPUT
          fi

      # ─── Core steps (only when run=true) ────────────────────────────────
      - uses: actions/checkout@v4
        if: steps.gate.outputs.run == 'true'

      # 1️⃣ Set up Python & install Pybindgen early for gopy’s build.py
      - name: Set up Python
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        if: steps.gate.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pybindgen pytest pytest-asyncio

      # 2️⃣ Install the package and run integration tests
      - name: Install package
        if: steps.gate.outputs.run == 'true'
        run: pip install -e .

      - name: Run integration tests
        if: steps.gate.outputs.run == 'true'
        run: pytest -q -m integration
