name: Update Verifier
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.2.3)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-verifier:
    runs-on: ubuntu-latest
    steps:
      # Generate token for GitHub App
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout with the app token
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: >-
          python3 -m
          pip install
          toml
          --user

      - name: Validate version format
        run: |
          VERSION="${{ inputs.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Expected: X.Y.Z (e.g., 1.2.3)"
            exit 1
          fi
          echo "Using version: $VERSION"

      - name: Update verifier and bump version
        run: |
          # Use Verifier Release Bot for commits
          git config --local user.email "1461927+verifier-release-bot[bot]@users.noreply.github.com"
          git config --local user.name "verifier-release-bot[bot]"

          # Bump version using our script
          python3 scripts/bump_version.py --version ${{ inputs.version }}

          # Check if there are any changes to commit
          if git diff --exit-code pyproject.toml; then
            echo "No changes to version"
          else
            git add pyproject.toml
            git commit -m "chore: bump version to ${{ inputs.version }}"
            git push origin main
          fi
